/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Marjori Barros
 */
<<<<<<< HEAD
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaProcessos extends javax.swing.JFrame {
       private String tipoUsuario;
=======
public class TelaProcessos extends javax.swing.JFrame {
>>>>>>> 06c877f18a4b3a1dda1dab94ab8544262e3d8241

    /**
     * Creates new form TelaProcessos
     */
    public TelaProcessos() {
<<<<<<< HEAD
    initComponents();  
    setLocationRelativeTo(null);
    this.tipoUsuario = "Visitante";
    setTitle("Gerenciamento de Processos - Visitante");
    configurarPermissoes("Visitante");
    destacarBotaoAtual(); 
    atualizarLabelUsuario();
    }
    
    public TelaProcessos(String tipoUsuario) {
    initComponents();
    setLocationRelativeTo(null);
    this.tipoUsuario = tipoUsuario; 
    setTitle("Gerenciamento de Processos - " + tipoUsuario);
    configurarPermissoes(tipoUsuario);
    carregarProcessos();
    atualizarLabelUsuario();
}
    private void atualizarLabelUsuario() {
    System.out.println("DEBUG: atualizarLabelUsuario() chamado - tipoUsuario = " + tipoUsuario);
    jLabel2.setText("Bem-vindo(a), " + tipoUsuario + "!");
    System.out.println("DEBUG: Texto definido para: " + jLabel2.getText());
}

=======
        initComponents();
    }
>>>>>>> 06c877f18a4b3a1dda1dab94ab8544262e3d8241

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBuscarProcesso = new javax.swing.JButton();
        btnNovoProcesso = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnProcessos = new javax.swing.JButton();
        btnManuais = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciar Processos");

        btnBuscarProcesso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarProcesso.setText(" Buscar..");
        btnBuscarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProcessoActionPerformed(evt);
            }
        });

        btnNovoProcesso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNovoProcesso.setText("+ Novo Processo");
        btnNovoProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProcessoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnUsuario.setText("Usuários");
        btnUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUsuario.setBorderPainted(false);
        btnUsuario.setContentAreaFilled(false);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnProcessos.setText("Processos");
        btnProcessos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnProcessos.setBorderPainted(false);
        btnProcessos.setContentAreaFilled(false);

        btnManuais.setText("Manuais");
        btnManuais.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnManuais.setBorderPainted(false);
        btnManuais.setContentAreaFilled(false);
        btnManuais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManuaisActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManuais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcessos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManuais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(14, 14, 14))
        );

        jLabel2.setText("Bem-vindo(a), [Usuário]! ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBuscarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnNovoProcesso))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGap(46, 46, 46)))
                        .addContainerGap(162, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarProcesso)
                    .addComponent(btnNovoProcesso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProcessoActionPerformed
<<<<<<< HEAD
    new TelaProcessosCadastrados(tipoUsuario).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBuscarProcessoActionPerformed

    private void btnNovoProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProcessoActionPerformed
       new TelaCadastroDeProcessos(tipoUsuario).setVisible(true); 
       this.dispose();
    }//GEN-LAST:event_btnNovoProcessoActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
    new TelaDashboard(tipoUsuario).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
    new TelaUsuarios(tipoUsuario).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
      int confirm = JOptionPane.showConfirmDialog(this, 
        "Deseja realmente sair do sistema?", "Confirmação", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        new TelaLogin().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnManuaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManuaisActionPerformed
    new TelaManuais(tipoUsuario).setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_btnManuaisActionPerformed

    private void destacarBotaoAtual() {
    // Resetar todos os botões
    btnDashboard.setBackground(null);
    btnUsuario.setBackground(null);
    btnProcessos.setBackground(Color.LIGHT_GRAY); // Destacar atual
    btnManuais.setBackground(null);
    
    // Destacar texto
    btnProcessos.setFont(btnProcessos.getFont().deriveFont(Font.BOLD));
}
    private void configurarPermissoes(String tipoUsuario) {
    boolean podeGerenciar = tipoUsuario.equals("Administrador") || 
                           tipoUsuario.equals("Direção") ||
                           tipoUsuario.equals("Gerência");
    
    btnNovoProcesso.setEnabled(podeGerenciar);
    
    // Feedback visual
    if (!podeGerenciar) {
        btnNovoProcesso.setToolTipText("Acesso restrito para " + tipoUsuario);
        btnNovoProcesso.setBackground(Color.LIGHT_GRAY);
    }
}
    private void navegarParaTelaSegura(Runnable acao, String nomeTela) {
    try {
        acao.run();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Erro ao abrir " + nomeTela + ": " + e.getMessage(),
            "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
    private void carregarProcessos() {
    try (Connection conn = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/integra_inicial", "root", "l5PV3IYH@")) {
        
        String sql = "SELECT p.id_processo, p.descricao, s.nome_setor " +
                     "FROM Processos p LEFT JOIN Setores s ON p.setor_id = s.id_setor";
        
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Descrição");
        model.addColumn("Setor");
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_processo"),
                rs.getString("descricao"),
                rs.getString("nome_setor")
            });
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar processos: " + e.getMessage());
    }
}

=======
        // 1. Criar uma instância (um objeto) da tela de cadastro
        TelaProcessosCadastrados telaCadastro = new TelaProcessosCadastrados();

        // 2. Tornar essa nova tela visível para o usuário
        telaCadastro.setVisible(true);

        // 3. Fechar a tela atual de listagem
        this.dispose();
    }//GEN-LAST:event_btnBuscarProcessoActionPerformed

    private void btnNovoProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProcessoActionPerformed
        // 1. Criar uma instância (um objeto) da tela de cadastro
        TelaCadastroDeProcessos telaCadastro = new TelaCadastroDeProcessos();

        // 2. Tornar essa nova tela visível para o usuário
        telaCadastro.setVisible(true);

        // 3. Fechar a tela atual de listagem
        this.dispose();
    }//GEN-LAST:event_btnNovoProcessoActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        new TelaDashboard().setVisible(true); // Abre a tela de dashboard
        this.dispose(); // Fecha o dashboard
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        new TelaUsuarios().setVisible(true); // Abre a tela de usuários
        this.dispose(); // Fecha o dashboard
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new TelaLogin().setVisible(true); // Volta para a tela de login
        this.dispose(); // Fecha o dashboard
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnManuaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManuaisActionPerformed
            new TelaManuais().setVisible(true); // Vai pra Tela de Manuais
        this.dispose(); // Fecha o dashboard
    }//GEN-LAST:event_btnManuaisActionPerformed

>>>>>>> 06c877f18a4b3a1dda1dab94ab8544262e3d8241
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProcessos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProcessos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProcesso;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnManuais;
    private javax.swing.JButton btnNovoProcesso;
    private javax.swing.JButton btnProcessos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
<<<<<<< HEAD


=======
>>>>>>> 06c877f18a4b3a1dda1dab94ab8544262e3d8241
}
